name = "guillaume-sax-contract-mail"
main = "src/index.mjs"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "https://guillaumesax.fr"
MAIL_FROM = "Guillaume Sax <contrats@guillaumesax.fr>"
MAIL_TO = "contact@guillaumesax.fr"
