name = "guillaume-sax-contract-mail"
account_id = "3b6e3b3a1c4600b8cfceb459a2fa1f02"
main = "src/index.mjs"
compatibility_date = "2026-09-01"

[vars]
ALLOWED_ORIGIN = "https://guillaumesax.fr"
MAIL_FROM = "Guillaume Sax <contrats@mail.guillaumesax.fr>"
MAIL_TO = "contact@guillaumesax.fr"
