import { StrictMode, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowUpRight, Check, Clock3, Download, Mail, Phone, PlugZap, ShieldCheck, Speaker, Sun, Umbrella, CarFront, GlassWater, Utensils, Copy } from 'lucide-react';
import './fiche-technique.css';

const pdf = './Fiche_Technique_2026.pdf';
const chapters = [{ id: 'installation', label: 'Installation' }, { id: 'sonorisation', label: 'Sonorisation' }, { id: 'environnement', label: 'Espace de jeu' }, { id: 'accueil', label: 'Accueil' }];
function App() {
  const [active, setActive] = useState('installation');
  const [notice, setNotice] = useState('');
  useEffect(() => {
    const observer = new IntersectionObserver(entries => {
      entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('visible'); observer.unobserve(entry.target); } });
    }, { threshold: .08 });
    document.querySelectorAll('[data-reveal]').forEach(el => observer.observe(el));
    const sections = new IntersectionObserver(entries => {
      entries.forEach(entry => { if (entry.isIntersecting) setActive(entry.target.id); });
    }, { rootMargin: '-15% 0px -55% 0px' });
    chapters.forEach(({ id }) => { const el = document.getElementById(id); if (el) sections.observe(el); });
    return () => { observer.disconnect(); sections.disconnect(); };
  }, []);
  const copy = async () => {
    try { await navigator.clipboard.writeText(window.location.href.split('#')[0]); setNotice('Lien copié. Vous pouvez le transmettre au lieu ou à votre organisateur.'); }
    catch { setNotice('La copie est indisponible. Copiez l’adresse de cette page depuis votre navigateur.'); }
  };
  return <>
    <a className="skip-link" href="#contenu">Aller au contenu</a>
    <header className="topbar"><div className="brand">Guillaume <em>Sax</em><span>LES DÉTAILS FONT L’HARMONIE</span></div><span className="eyebrow">FICHE TECHNIQUE · 2026</span></header>
    <main id="contenu">
      <section className="hero wrap">
        <div className="hero-copy"><p className="eyebrow"><span /> LE GUIDE TECHNIQUE · 2026</p><h1>Tout préparer.<br />Laisser place à<br /><em>la musique.</em></h1><p className="lead">Quelques détails à anticiper ensemble, pour une prestation fluide et une journée en toute sérénité.</p><a className="button primary" href={pdf} download><Download size={16} aria-hidden="true" /> Télécharger la fiche PDF <ArrowUpRight size={16} aria-hidden="true" /></a><p className="micro">À transmettre à votre lieu, organisateur·rice ou régisseur.</p></div>
        <aside className="essentials" aria-labelledby="essentials-title"><div className="card-top"><span className="eyebrow">EN UN COUP D’ŒIL</span><span className="edition">GS / 26</span></div><h2 id="essentials-title">Les essentiels</h2><div className="essential"><Clock3 aria-hidden="true" /><div><strong>45 <em>min</em></strong><p>Installation & balance</p></div><span className="ordinal">01</span></div><div className="essential"><Speaker aria-hidden="true" /><div><strong>Stéréo</strong><p>Diffusion amplifiée obligatoire</p></div><span className="ordinal">02</span></div><div className="essential"><Umbrella aria-hidden="true" /><div><strong>À l’abri</strong><p>Protection obligatoire en extérieur</p></div><span className="ordinal">03</span></div><a href="#installation" className="explore">Tous les détails <ArrowDown size={17} aria-hidden="true" /></a></aside>
      </section>
      <div className="chapter-bar"><nav className="wrap" aria-label="Dans cette fiche"><span className="eyebrow">BIEN PRÉPARER</span>{chapters.map((chapter, i) => <a key={chapter.id} href={`#${chapter.id}`} aria-current={active === chapter.id ? 'location' : undefined}><span>0{i + 1}</span>{chapter.label}</a>)}</nav></div>
      <div className="wrap chapters">
        <section className="chapter" id="installation" data-reveal><div className="chapter-title"><span className="section-number">01 /</span><p className="eyebrow">AVANT LES PREMIÈRES NOTES</p><h2>Installation<br /><em>& balances.</em></h2><p>Un temps dédié pour installer le matériel et trouver le juste équilibre sonore.</p></div><div className="chapter-content"><div className="timing"><div><strong>1 <em>h max.</em></strong><p>Arrivée sur place avant le début de la prestation.</p></div><div><strong>45 <em>min</em></strong><p>Pour l’installation et la balance, idéalement sans public.</p></div></div><div className="note"><Check size={19} aria-hidden="true" /><p>Merci de prévoir <strong>un·e référent·e pour l’accueil</strong> et l’accompagnement du parking jusqu’au lieu de prestation.</p></div></div></section>
        <section className="chapter" id="sonorisation" data-reveal><div className="chapter-title"><span className="section-number">02 /</span><p className="eyebrow">LE CONFORT D’ÉCOUTE</p><h2>Matériel<br /><em>& sonorisation.</em></h2><p>Une diffusion adaptée au lieu pour que chaque nuance trouve sa place.</p></div><div className="chapter-content"><div className="spec-row"><Speaker aria-hidden="true" /><div><h3>Une diffusion amplifiée en stéréo</h3><p>Restitution en stéréo obligatoire. Les types d’enceintes sont à valider en amont.</p></div></div><div className="spec-row"><PlugZap aria-hidden="true" /><div><h3>Les connexions à prévoir</h3><ul><li><strong>2 câbles XLR de 5 m minimum chacun.</strong></li><li>Un enrouleur électrique avec <strong>au moins 4 prises reliées à la terre.</strong></li></ul></div></div><p className="boundary">Je n’assure pas la manipulation de matériel lourd : enceintes, amplificateurs ou structures.</p><div className="option"><p className="eyebrow">UNE OPTION POUR VOUS SIMPLIFIER LES CHOSES</p><h3>Besoin d’une sonorisation ?</h3><p>Je peux fournir le système si nécessaire, avec supplément et sur devis.</p><a href="mailto:guillaume.sax@gmail.com?subject=Sonorisation%20de%20notre%20%C3%A9v%C3%A9nement">En discuter ensemble <ArrowUpRight size={16} aria-hidden="true" /></a></div></div></section>
        <section className="chapter" id="environnement" data-reveal><div className="chapter-title"><span className="section-number">03 /</span><p className="eyebrow">LE BON EMPLACEMENT</p><h2>Un espace<br /><em>pour jouer.</em></h2><p>À l’intérieur comme à l’extérieur, quelques conditions essentielles pour accueillir la musique.</p></div><div className="chapter-content"><div className="table-spec"><div className="table-drawing" aria-hidden="true"><span>50 cm min.</span><div /><span>50 cm min.</span></div><div><h3>Une table stable</h3><p>Dimensions minimales :<br /><strong>50 × 50 cm.</strong></p></div></div><div className="outdoor"><Umbrella size={25} aria-hidden="true" /><div><p className="eyebrow">EN EXTÉRIEUR · OBLIGATOIRE</p><h3>Un espace protégé</h3><p>Prévoyez un barnum, un préau ou un abri. <strong>Le saxophone ne peut être joué sous la pluie.</strong></p></div></div><div className="note"><Sun size={21} aria-hidden="true" /><p>Pour une prestation en plein soleil, prévoyez une <strong>zone ombragée.</strong></p></div></div></section>
        <section className="chapter" id="accueil" data-reveal><div className="chapter-title"><span className="section-number">04 /</span><p className="eyebrow">LES ATTENTIONS PRATIQUES</p><h2>Accès<br /><em>& accueil.</em></h2><p>Des détails simples qui facilitent l’arrivée et le bon déroulement de la prestation.</p></div><div className="chapter-content"><div className="spec-row"><CarFront aria-hidden="true" /><div><h3>Un accès facilité</h3><p>Un parking proche pour le déchargement, ainsi qu’une place de parking réservée et sécurisée.</p></div></div><div className="spec-row"><GlassWater aria-hidden="true" /><div><h3>De l’eau dès l’installation</h3><p>Une bouteille d’eau disponible dès mon arrivée pour l’installation.</p></div></div><div className="spec-row"><Utensils aria-hidden="true" /><div><h3>Si la prestation finit après 22 h</h3><p>Un repas complet et chaud est à prévoir.</p></div></div></div></section>
      </div>
      <section className="contact-section" data-reveal><div className="wrap contact-grid"><div><p className="eyebrow">ANTICIPONS ENSEMBLE</p><h2>Il n’y a que<br /><em>des solutions.</em></h2></div><div><p>Une question sur le lieu, le matériel ou l’organisation ? Prenons le temps d’en parler pour préparer au mieux votre journée.</p><a className="contact-link" href="mailto:guillaume.sax@gmail.com"><Mail size={18} aria-hidden="true" /> guillaume.sax@gmail.com <ArrowUpRight size={17} aria-hidden="true" /></a><a className="contact-link" href="tel:+33659448834"><Phone size={18} aria-hidden="true" /> 06 59 44 88 34 <ArrowUpRight size={17} aria-hidden="true" /></a><div className="share-actions"><button className="button" onClick={copy}><Copy size={16} aria-hidden="true" /> Copier le lien de la fiche</button><a className="pdf-link" href={pdf} download><Download size={16} aria-hidden="true" /> Le PDF</a></div><p className="notice" role="status">{notice}</p></div></div></section>
      <section className="legal wrap"><div><ShieldCheck size={22} aria-hidden="true" /><h2>En toute confiance</h2></div><p>Prestation couverte par une assurance Responsabilité Civile Professionnelle (RC Pro).<br />SIRET : 819 503 434 00030.</p><p className="legal-detail">Afin de garantir une prestation fluide et conforme à vos attentes, il est important que les éléments indiqués dans cette fiche soient respectés. En cas d’imprévu ou de conditions non réunies, des ajustements ou des frais supplémentaires pourraient être nécessaires, voire limiter la faisabilité de la prestation. Je reste bien entendu disponible pour anticiper toute situation et trouver ensemble les solutions les plus adaptées.</p></section>
    </main>
    <footer className="footer wrap"><div className="brand">Guillaume <em>Sax</em></div><a href="#contenu">Retour en haut ↑</a><p className="destination-url">https://guillaumesax.fr/fiche-technique</p></footer>
  </>;
}
createRoot(document.getElementById('root')!).render(<StrictMode><App /></StrictMode>);


